[workspace]
resolver = "2"

members = [ "ckb-vote-test-tool",
  # Please don't remove the following line, we use it to automatically
  # detect insertion point for newly generated crates.
  # @@INSERTION_POINT@@
  "contracts/ring-signature-verify",
  "tests",
]

[profile.release]
overflow-checks = true
strip = true
codegen-units = 1
